### ISSUE TITLE
How's it going?

### ISSUE THREAD

**Issue by MortalMercury** [Satisfactory-Clips-Archive/Media-Archive-Metadata#2]
Just wondering, I hope the PC mishap didn't screw up your real job.

**Comment by SignpostMarv** [comment]
dayjob unaffected, thanks :)

PC is due back next week.

**Comment by SignpostMarv** [comment]
by "next week", I unknowingly meant "this afternoon" 🤷‍♂️

**Comment by MortalMercury** [comment]
Tends to happen sometimes haha
